//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.example.demorest.Entity;

import java.io.Serializable;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Response">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="ReturnCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   <element name="ReturnMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="ResponseMidUserDetails">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="CivilIdNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   <element name="FullNameAr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="FullNameEn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="NationalityEn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="NationalityAr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="MobileNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <element name="EmailId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="BloodGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="CardSerialNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <element name="CardExpiryDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <element name="DocumentNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   <element name="PassportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="MoiReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <element name="SponsorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="Governorate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="Area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="PaciBuildingNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <element name="BuildingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="FloorNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   <element name="BuildingNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   <element name="BlockNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   <element name="UnitNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   <element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="UnitType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="LastUpdTs" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="command" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="exitState" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       <attribute name="exitStateType" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       <attribute name="exitStateMsg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "responseMidUserDetails"
})
@XmlRootElement(name = "InquireMidUserDetailsExport",namespace="")
public class InquireMidUserDetailsExport implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(name = "Response", required = true)
    protected InquireMidUserDetailsExport.Response response;
//    @XmlElement(name = "ResponseMidUserDetails", required = true)
//    protected InquireMidUserDetailsExport.ResponseMidUserDetails responseMidUserDetails;
    @XmlAttribute(name = "command")
    protected String command;
    @XmlAttribute(name = "exitState")
    protected Byte exitState;
    @XmlAttribute(name = "exitStateType")
    protected Byte exitStateType;
    @XmlAttribute(name = "exitStateMsg")
    protected String exitStateMsg;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link InquireMidUserDetailsExport.Response }
     *     
     */
    public InquireMidUserDetailsExport.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquireMidUserDetailsExport.Response }
     *     
     */
    public void setResponse(InquireMidUserDetailsExport.Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the responseMidUserDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InquireMidUserDetailsExport.ResponseMidUserDetails }
     *     
     */
//    public InquireMidUserDetailsExport.ResponseMidUserDetails getResponseMidUserDetails() {
//        return responseMidUserDetails;
//    }

    /**
     * Sets the value of the responseMidUserDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquireMidUserDetailsExport.ResponseMidUserDetails }
     *     
     */
//    public void setResponseMidUserDetails(InquireMidUserDetailsExport.ResponseMidUserDetails value) {
//        this.responseMidUserDetails = value;
//    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the exitState property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getExitState() {
        return exitState;
    }

    /**
     * Sets the value of the exitState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setExitState(Byte value) {
        this.exitState = value;
    }

    /**
     * Gets the value of the exitStateType property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getExitStateType() {
        return exitStateType;
    }

    /**
     * Sets the value of the exitStateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setExitStateType(Byte value) {
        this.exitStateType = value;
    }

    /**
     * Gets the value of the exitStateMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExitStateMsg() {
        return exitStateMsg;
    }

    /**
     * Sets the value of the exitStateMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExitStateMsg(String value) {
        this.exitStateMsg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="ReturnCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         <element name="ReturnMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnCode",
        "returnMessage"
    })
    public static class Response {

        @XmlElement(name = "ReturnCode")
        protected byte returnCode;
        @XmlElement(name = "ReturnMessage", required = true)
        protected String returnMessage;

        /**
         * Gets the value of the returnCode property.
         * 
         */
        public byte getReturnCode() {
            return returnCode;
        }

        /**
         * Sets the value of the returnCode property.
         * 
         */
        public void setReturnCode(byte value) {
            this.returnCode = value;
        }

        /**
         * Gets the value of the returnMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnMessage() {
            return returnMessage;
        }

        /**
         * Sets the value of the returnMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnMessage(String value) {
            this.returnMessage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="CivilIdNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         <element name="FullNameAr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="FullNameEn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="NationalityEn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="NationalityAr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="MobileNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <element name="EmailId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="BloodGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="CardSerialNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <element name="CardExpiryDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <element name="DocumentNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         <element name="PassportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="MoiReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <element name="SponsorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="Governorate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="Area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="PaciBuildingNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <element name="BuildingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="FloorNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         <element name="BuildingNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         <element name="BlockNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         <element name="UnitNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         <element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="UnitType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="LastUpdTs" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
   
    

}
